const ADMIN_EMAIL=['qqwweenn27','gmail.com'].join('@');const ADMIN_FN=SB_URL+'/functions/v1/admin-manage';
function isAdmin(){return !!state.user&&String(state.user.email||'').toLowerCase()===ADMIN_EMAIL}
function admin(){if(!isAdmin())return `<div class="auth"><div class="authbox"><div class="authlogo"><div class="logo">ج</div><h1>بوابة الإدارة</h1><p>الدخول للمشرف المعتمد فقط</p></div><div class="notice warning">🔐 البريد المعتمد: <b>${ADMIN_EMAIL}</b></div><div class="form"><input id="ae" type="email" value="${ADMIN_EMAIL}"><input id="ap" type="password" placeholder="كلمة المرور"><button class="btn primary full" onclick="adminLogin()">دخول آمن</button><button class="btn secondary full" onclick="go('home')">العودة</button></div></div></div>`;return layout(`${pageHead('لوحة الإدارة')}<div class="notice success">🛡️ لوحة المشرف • ${ADMIN_EMAIL}</div><div class="adminnav"><button onclick="adminTab('overview')">📊 الرئيسية</button><button onclick="adminTab('add')">➕ إضافة</button><button onclick="adminTab('people')">👥 الحسابات</button><button onclick="adminTab('restaurants')">🍽️ المطاعم</button><button onclick="adminTab('orders')">📦 الطلبات</button><button onclick="adminTab('settings')">⚙️ الإعدادات</button></div><div id="adminBody">${adminBody()}</div>`)}
function adminTab(t){state.adminTab=t;render()}
async function adminLogin(){const e=document.getElementById('ae').value.trim().toLowerCase(),p=document.getElementById('ap').value;if(e!==ADMIN_EMAIL)return toast('البريد غير مصرح');try{const r=await fetch(SB_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});const d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||'بيانات الدخول غير صحيحة');state.user={name:'مشرف جيبلي',email:e,access_token:d.access_token,role:'admin'};save();go('admin')}catch(x){toast(x.message)}}
function adminBody(){const t=state.adminTab||'overview';if(t==='add')return addStaff();if(t==='people')return people();if(t==='restaurants')return restaurantsAdmin();if(t==='orders')return adminOrders();if(t==='settings')return adminSettings();return `<div class="statgrid section"><div class="stat"><span>الطلبات</span><b>${state.orders.length}</b></div><div class="stat"><span>المستخدمون</span><b id="au">—</b></div><div class="stat"><span>السائقون</span><b id="ad">—</b></div><div class="stat"><span>المطاعم</span><b id="ar">—</b></div></div><div class="cards"><div class="card"><b>🚗 إدارة السائقين</b><p class="meta">إضافة حساب السائق وبيانات المركبة من زر الإضافة.</p></div><div class="card"><b>🍽️ إدارة أصحاب المطاعم</b><p class="meta">إنشاء المالك وربط المطعم معه مباشرة.</p></div><div class="notice">🔒 العمليات الحساسة تنفذ عبر Edge Function محمية ولا تستخدم المفتاح السري داخل المتصفح.</div></div>`}
function addStaff(){return `<div class="tabs"><button class="tab active" id="dt" onclick="addMode('driver')">🚗 سائق</button><button class="tab" id="rt" onclick="addMode('restaurant_owner')">🍽️ صاحب مطعم</button></div><div id="staffForm">${staffForm('driver')}</div>`}
function addMode(r){document.getElementById('staffForm').innerHTML=staffForm(r);document.getElementById('dt').classList.toggle('active',r==='driver');document.getElementById('rt').classList.toggle('active',r!=='driver')}
function staffForm(r){return `<div class="card form"><h2>${r==='driver'?'إضافة سائق':'إضافة صاحب مطعم'}</h2><input id="sn" placeholder="الاسم الكامل *"><input id="se" type="email" placeholder="البريد الإلكتروني *"><input id="sp" type="password" placeholder="كلمة مرور الحساب *"><input id="sph" placeholder="الهاتف"><div id="extra">${r==='driver'?'<input id="vm" placeholder="موديل المركبة"><input id="vp" placeholder="رقم اللوحة">':'<input id="rn" placeholder="اسم المطعم *"><textarea id="rd" class="textarea" placeholder="وصف المطعم"></textarea><input id="ra" placeholder="عنوان المطعم"><input id="rf" type="number" value="1500" placeholder="أجرة التوصيل">'}</div><button class="btn primary" onclick="createStaff('${r}')">حفظ وإضافة ✅</button></div>`}
async function callAdmin(action,data){if(!isAdmin())throw Error('غير مصرح');const r=await fetch(ADMIN_FN,{method:'POST',headers:{apikey:SB_KEY,Authorization:'Bearer '+state.user.access_token,'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'فشلت العملية');return d}
async function createStaff(role){const n=document.getElementById('sn').value.trim(),e=document.getElementById('se').value.trim(),p=document.getElementById('sp').value;if(!n||!e||p.length<8)return toast('أكمل الاسم والبريد وكلمة المرور');const d={full_name:n,email:e,password:p,phone:document.getElementById('sph').value,role};if(role==='driver')Object.assign(d,{vehicle_model:document.getElementById('vm').value,vehicle_plate:document.getElementById('vp').value});else Object.assign(d,{restaurant_name:document.getElementById('rn').value,restaurant_description:document.getElementById('rd').value,restaurant_address:document.getElementById('ra').value,delivery_fee:Number(document.getElementById('rf').value||0)});try{await callAdmin('create_user',d);toast('تمت الإضافة بنجاح ✅');state.adminTab='people';render();loadAdmin()}catch(x){toast(x.message)}}
async function loadAdmin(){if(!isAdmin())return;try{const [u,r]=await Promise.all([callAdmin('list_users'),callAdmin('list_restaurants')]);window.ac={u:u.profiles||[],r:r.restaurants||[]};const a=document.getElementById('au'),b=document.getElementById('ad'),c=document.getElementById('ar');if(a)a.textContent=ac.u.length;if(b)b.textContent=ac.u.filter(x=>x.role==='driver').length;if(c)c.textContent=ac.r.length;renderPeople()}catch(e){console.log(e)}}
function people(){return `<div class="sectionhead"><h2>الحسابات</h2><button class="link" onclick="loadAdmin()">تحديث ↻</button></div><div id="peopleList"><div class="empty">جارِ التحميل...</div></div>`}
function renderPeople(){const b=document.getElementById('peopleList');if(!b)return;const u=window.ac?.u||[];b.innerHTML=u.length?`<div class="cards">${u.map(x=>`<div class="card order"><span style="font-size:27px">${x.role==='driver'?'🚗':'🍽️'}</span><div style="flex:1"><b>${esc(x.full_name||'بدون اسم')}</b><div class="meta">${x.role==='driver'?'سائق':'صاحب مطعم'} • ${esc(x.phone||'')}</div></div><span class="status">نشط</span></div>`).join('')}</div>`:'<div class="empty">لا توجد حسابات</div>'}
function restaurantsAdmin(){const r=window.ac?.r||[];return `<div class="sectionhead"><h2>المطاعم</h2><button class="link" onclick="loadAdmin()">تحديث ↻</button></div><div class="cards">${r.length?r.map(x=>`<div class="card order"><span style="font-size:27px">🍽️</span><div style="flex:1"><b>${esc(x.name)}</b><div class="meta">${esc(x.address_text||'بدون عنوان')} • ${money(x.delivery_fee||0)}</div></div><button class="btn ${x.is_open?'primary':'secondary'}" onclick="toggleRest('${x.id}',${!x.is_open})">${x.is_open?'مفتوح':'مغلق'}</button></div>`).join(''):'<div class="empty">لا توجد مطاعم</div>'}</div>`}
async function toggleRest(id,v){try{await callAdmin('set_restaurant_open',{id,is_open:v});toast('تم التحديث');loadAdmin()}catch(e){toast(e.message)}}
function adminSettings(){return `<div class="cards"><div class="card"><h3>🔐 الأمان</h3><p class="meta">الوصول محصور بالبريد المعتمد، والخادم يعيد التحقق من هوية المشرف.</p></div><div class="card"><h3>💰 التسعير</h3><div class="row"><input value="1500" placeholder="بدء التكسي"><input value="500" placeholder="لكل كم"></div><button class="btn primary full" onclick="toast('جاهز للربط بإعدادات التسعير')">حفظ</button></div></div>`}
const oldProfileFn=profile;profile=function(){if(!state.user)return oldProfileFn();const b=isAdmin()?`<button class="card" style="text-align:right;border-color:#6b5209" onclick="go('admin')">🛡️ لوحة الإدارة <span style="float:left">‹</span></button>`:'';return layout(`${pageHead('حسابي')}<div class="card"><b>${esc(state.user.name||'مستخدم جيبلي')}</b><div class="meta">${esc(state.user.email||'')}</div></div><div class="section cards">${b}<button class="btn danger full" onclick="logout()">تسجيل الخروج</button></div>`)}
const appRender=render;render=function(){appRender();if(state.page==='admin'&&isAdmin())setTimeout(loadAdmin,30)};render();